env:
  global:
    - CC_TEST_REPORTER_ID=2aa3cf15f3b3188b87f35cbade782d7143bf7b4adf4d0210ef0d58b1b31645c2
language: node_js
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '8'
script: npm run test:ci
after_script:
  - ./cc-test-reporter after-build -t lcov --exit-code $TRAVIS_TEST_RESULT
after_success:
  - npm run travis-deploy-once "npm run semantic-release"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
